spring:
  application:
    name: reservas-service

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8080

eureka:
  client: 
  service-url:
  defaultZone: http://localhost:8761/eureka/
  register-with-eureka: false   # ⬅️ desactivado temporalmente
  fetch-registry: false         # ⬅️ desactivado temporalmente

